### ISSUE TITLE
Building "Bar" seems broken

### ISSUE THREAD

**Issue by DennisRas** [MrEliasen/path-to-power#50] opened 2018-02-11 19:46 UTC
## Is this a bug report?
Yes

## Steps to Reproduce
1. Log into the game
2. Move to London (North 4 / East 28)
3. Click the building "Bar"

## Expected Behavior
Description of the building maybe and a list of commands of the build that I can use.

## Actual Behavior
It gives me the following:
![](https://i.imgur.com/kQkvJVj.png)

If I type /shops (assumed because of the text in the screenshot above) nothing happens.
If I type /shop (suggested by the command list) nothing happens.

## Possible Solution
Fix /shop? Not sure if the building is missing some features at this point.

**Comment by MrEliasen** [comment] 2018-02-12 09:55
Duplicate of #2 

The building is merely added as a shell, but lacks all its functionality :)

**Closed** 2018-02-12 22:24 UTC
Labels: bug, duplicate
